### ISSUE TITLE
prog.CreateTestMainPackage undefined (type *ssa.Program has no field or method CreateTestMainPackage

### ISSUE THREAD

**Issue by MatthiasPetermann** [visualfc/gotools#16]
Hello, 

while building the gotools (originally as part of liteidex, but reproducable also standalone) I get the following error:

```
mpeterma@x230 ~> go get -u github.com/visualfc/gotools
# github.com/visualfc/gotools/oracle/oracle
go/pkg/mod/github.com/visualfc/gotools@v1.3.6/oracle/oracle/oracle.go:192:16: prog.CreateTestMainPackage undefined (type *ssa.Program has no field or method CreateTestMainPackage)
```

My host OS is  NetBSD so there might be a environment issue on my side(?). Anyway, I did some research an found some note on deprecation of the affected method:

https://github.com/golang/go/issues/48547

Is this something which could be fixed in gotools, or is the issue not closely related to it?

Kind regards
Matthias

**Comment by visualfc** [comment]
> Hello,
> 
> while building the gotools (originally as part of liteidex, but reproducable also standalone) I get the following error:
> 
> ```
> mpeterma@x230 ~> go get -u github.com/visualfc/gotools
> # github.com/visualfc/gotools/oracle/oracle
> go/pkg/mod/github.com/visualfc/gotools@v1.3.6/oracle/oracle/oracle.go:192:16: prog.CreateTestMainPackage undefined (type *ssa.Program has no field or method CreateTestMainPackage)
> ```
> 
> My host OS is NetBSD so there might be a environment issue on my side(?). Anyway, I did some research an found some note on deprecation of the affected method:
> 
> [golang/go#48547](https://github.com/golang/go/issues/48547)
> 
> Is this something which could be fixed in gotools, or is the issue not closely related to it?
> 
> Kind regards Matthias

golang.org/x/tools v0.18 remove prog.CreateTestMainPackage

**Comment by visualfc** [comment]
fixed by https://github.com/visualfc/gotools/pull/17

**Comment by MatthiasPetermann** [comment]
Thank you so much - this fixed it for me.
