### ISSUE TITLE
gotools does not update

### ISSUE THREAD

**Issue by gshields** [visualfc/gotools#18]
go get -u github.com/visualfc/gotools
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
# github.com/visualfc/gotools/oracle/oracle
go\pkg\mod\github.com\visualfc\gotools@v1.3.6\oracle\oracle\oracle.go:192:16: prog.CreateTestMainPackage undefined (type *ssa.Program has no field or method CreateTestMainPackage)

**Comment by visualfc** [comment]
go install github.com/visualfc/gotools@latest
