### ISSUE TITLE
Allow user-defined testargs from env variable

### ISSUE THREAD

**Issue by jdoklovic** [visualfc/gotools#6]
I use LiteIde and need to pass build tags to the test commands via the -tags option.
This works for everything except the FileTest command since it's using gotools gotest which just hardcodes the testargs.

It would be better if it had default options but let the user override them with a TESTARGS environment variable.

**Comment by visualfc** [comment]
fix it
https://github.com/visualfc/gotools/commit/02485b4375ed08a826fbff6c049e1c3182e0885d
